#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.13 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xfd70;
constexpr uint24_t FX_DATA_BYTES = 163790;

constexpr uint16_t FX_SAVE_PAGE  = 0xfff0;
constexpr uint24_t FX_SAVE_BYTES = 2;

namespace Music
{
  constexpr uint24_t Song_MainTheme = 0x000000;
  constexpr uint24_t SFX_Death = 0x018580;
  constexpr uint24_t SFX_Victory = 0x018624;
  constexpr uint24_t SFX_XPGain = 0x0186D8;
  constexpr uint24_t SFX_Three_Inc = 0x0186EC;
  constexpr uint24_t SFX_Three_Dec = 0x018708;
  constexpr uint24_t SFX_PlayerBlip = 0x018724;
  constexpr uint24_t SFX_EnemyBlip = 0x018734;
  constexpr uint24_t SFX_Explosion = 0x018744;
  constexpr uint24_t SFX_DoubleBeep = 0x018788;
  constexpr uint24_t SFX_DoubleBeepDown = 0x018798;
  constexpr uint24_t SFX_Bet1 = 0x0187A8;
  constexpr uint24_t SFX_Bet2 = 0x0187B0;
  constexpr uint24_t SFX_Bet3 = 0x0187B8;
  constexpr uint24_t SFX_Bet4 = 0x0187C0;
  constexpr uint24_t SFX_Bet5 = 0x0187C8;
  constexpr uint24_t SFX_Bet6 = 0x0187D0;
  constexpr uint24_t SFX_Click = 0x0187D8;
  constexpr uint24_t SFX_SmallBlind = 0x0187E0;
  constexpr uint24_t SFX_BigBlind = 0x0187E8;
}

namespace Constants
{
  constexpr uint24_t temp_Count = 0x0187F8;
  constexpr uint24_t temp_6x5_00 = 0x0187F9;
  constexpr uint24_t temp_6x5_01 = 0x018817;
  constexpr uint24_t temp_6x5_02 = 0x018835;
  constexpr uint24_t temp_6x5_03 = 0x018853;
  constexpr uint24_t temp_6x5_04 = 0x018871;
  constexpr uint24_t temp_6x5_05 = 0x01888F;
  constexpr uint24_t temp_6x5_06 = 0x0188AD;
  constexpr uint24_t temp_6x5_07 = 0x0188CB;
  constexpr uint24_t temp_6x5_08 = 0x0188E9;
  constexpr uint24_t temp_6x5_09 = 0x018907;
  constexpr uint24_t temp_6x5_10 = 0x018925;
  constexpr uint24_t temp_6x5_11 = 0x018943;
  constexpr uint24_t temp_8x7_00 = 0x018961;
  constexpr uint24_t temp_8x7_01 = 0x018999;
  constexpr uint24_t temp_8x7_02 = 0x0189D1;
  constexpr uint24_t temp_8x7_03 = 0x018A09;
  constexpr uint24_t temp_8x7_04 = 0x018A41;
  constexpr uint24_t temp_8x7_05 = 0x018A79;
  constexpr uint24_t temp_8x7_06 = 0x018AB1;
  constexpr uint24_t temp_8x7_07 = 0x018AE9;
  constexpr uint24_t temp_8x7_08 = 0x018B21;
  constexpr uint24_t temp_8x7_09 = 0x018B59;
  constexpr uint24_t temp_8x7_10 = 0x018B91;
  constexpr uint24_t temp_8x7_11 = 0x018BC9;
  constexpr uint24_t temp_10x9_00 = 0x018C01;
  constexpr uint24_t temp_10x9_01 = 0x018C5B;
  constexpr uint24_t temp_10x9_02 = 0x018CB5;
  constexpr uint24_t temp_10x9_03 = 0x018D0F;
  constexpr uint24_t temp_10x9_04 = 0x018D69;
  constexpr uint24_t temp_10x9_05 = 0x018DC3;
  constexpr uint24_t temp_10x9_06 = 0x018E1D;
  constexpr uint24_t temp_10x9_07 = 0x018E77;
  constexpr uint24_t temp_10x9_08 = 0x018ED1;
  constexpr uint24_t temp_10x9_09 = 0x018F2B;
  constexpr uint24_t temp_10x9_10 = 0x018F85;
  constexpr uint24_t temp_10x9_11 = 0x018FDF;
  constexpr uint24_t temp_Levels = 0x019039;
}

namespace Images
{
  constexpr uint24_t PPOT = 0x0190A5;
  constexpr uint24_t Sound_Volume_Grey = 0x01C0A7;
  constexpr uint24_t Sound_Volume_White = 0x01C8E9;
  constexpr uint24_t Sound_Checkbox = 0x01D12B;
  constexpr uint24_t Title = 0x01D139;
  constexpr uint24_t Select = 0x01F9BB;
  constexpr uint24_t Hooray_00 = 0x021B7D;
  constexpr uint24_t Hooray_01 = 0x021D2F;
  constexpr uint24_t Hooray_02 = 0x021F71;
  constexpr uint24_t Hooray_03 = 0x0221B3;
  constexpr uint24_t Hooray_04 = 0x02234D;
  constexpr uint24_t Hooray_05 = 0x0224FF;
  constexpr uint24_t Hooray_06 = 0x0226B1;
  constexpr uint24_t HUD = 0x02275B;
  constexpr uint24_t Score_Numbers_Bottom = 0x022985;
  constexpr uint24_t Score_Numbers_Left = 0x022A83;
  constexpr uint24_t Score_Numbers_Right = 0x022B81;
  constexpr uint24_t Arrows = 0x022C7F;
  constexpr uint24_t HighScores = 0x022CCF;
  constexpr uint24_t Dealer = 0x0236C1;
  constexpr uint24_t Wave_Top = 0x0236D2;
  constexpr uint24_t Wave_Bot = 0x023E00;
  constexpr uint24_t Wave_Left = 0x02452E;
  constexpr uint24_t Wave_Right = 0x024B0C;
  constexpr uint24_t Magnets = 0x0250EA;
  constexpr uint24_t InGame = 0x025BCC;
  constexpr uint24_t Tile_0102 = 0x026FBA;
  constexpr uint24_t Tile_0403 = 0x027154;
  constexpr uint24_t Tile_1112 = 0x0272EE;
  constexpr uint24_t Tile_2221 = 0x027530;
  constexpr uint24_t Tile_3132 = 0x027772;
  constexpr uint24_t Tile_4142 = 0x02790C;
  constexpr uint24_t Tile_5152 = 0x027B4E;
  constexpr uint24_t Tile_6162 = 0x027CE8;
  constexpr uint24_t Cursor_X = 0x027F2A;
  constexpr uint24_t Cursor_Y = 0x027F8C;
  constexpr uint24_t Plus = 0x027F9A;
  constexpr uint24_t Minus = 0x027FB4;
}

