#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.13 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xfd7b;
constexpr uint24_t FX_DATA_BYTES = 160952;

constexpr uint16_t FX_SAVE_PAGE  = 0xfff0;
constexpr uint24_t FX_SAVE_BYTES = 2;

namespace Music
{
  constexpr uint24_t Song_MainTheme = 0x000000;
  constexpr uint24_t SFX_Death = 0x018580;
  constexpr uint24_t SFX_Victory = 0x018624;
  constexpr uint24_t SFX_XPGain = 0x0186D8;
  constexpr uint24_t SFX_Three_Inc = 0x0186EC;
  constexpr uint24_t SFX_Three_Dec = 0x018708;
  constexpr uint24_t SFX_PlayerBlip = 0x018724;
  constexpr uint24_t SFX_EnemyBlip = 0x018734;
  constexpr uint24_t SFX_Explosion = 0x018744;
  constexpr uint24_t SFX_DoubleBeep = 0x018788;
  constexpr uint24_t SFX_DoubleBeepDown = 0x018798;
  constexpr uint24_t SFX_Bet1 = 0x0187A8;
  constexpr uint24_t SFX_Bet2 = 0x0187B0;
  constexpr uint24_t SFX_Bet3 = 0x0187B8;
  constexpr uint24_t SFX_Bet4 = 0x0187C0;
  constexpr uint24_t SFX_Bet5 = 0x0187C8;
  constexpr uint24_t SFX_Bet6 = 0x0187D0;
  constexpr uint24_t SFX_Click = 0x0187D8;
  constexpr uint24_t SFX_SmallBlind = 0x0187E0;
  constexpr uint24_t SFX_BigBlind = 0x0187E8;
}

namespace Constants
{
  constexpr uint24_t temp_Count = 0x0187F8;
  constexpr uint24_t temp_6x5_00 = 0x0187F9;
  constexpr uint24_t temp_6x5_01 = 0x018817;
  constexpr uint24_t temp_6x5_02 = 0x018835;
  constexpr uint24_t temp_6x5_03 = 0x018853;
  constexpr uint24_t temp_6x5_04 = 0x018871;
  constexpr uint24_t temp_6x5_05 = 0x01888F;
  constexpr uint24_t temp_6x5_06 = 0x0188AD;
  constexpr uint24_t temp_6x5_07 = 0x0188CB;
  constexpr uint24_t temp_6x5_08 = 0x0188E9;
  constexpr uint24_t temp_6x5_09 = 0x018907;
  constexpr uint24_t temp_6x5_10 = 0x018925;
  constexpr uint24_t temp_6x5_11 = 0x018943;
  constexpr uint24_t temp_8x7_00 = 0x018961;
  constexpr uint24_t temp_8x7_01 = 0x018999;
  constexpr uint24_t temp_8x7_02 = 0x0189D1;
  constexpr uint24_t temp_8x7_03 = 0x018A09;
  constexpr uint24_t temp_8x7_04 = 0x018A41;
  constexpr uint24_t temp_8x7_05 = 0x018A79;
  constexpr uint24_t temp_8x7_06 = 0x018AB1;
  constexpr uint24_t temp_8x7_07 = 0x018AE9;
  constexpr uint24_t temp_8x7_08 = 0x018B21;
  constexpr uint24_t temp_8x7_09 = 0x018B59;
  constexpr uint24_t temp_8x7_10 = 0x018B91;
  constexpr uint24_t temp_8x7_11 = 0x018BC9;
  constexpr uint24_t temp_Levels = 0x018C01;
}

namespace Images
{
  constexpr uint24_t PPOT = 0x018C49;
  constexpr uint24_t Sound_Volume_Grey = 0x01BC4B;
  constexpr uint24_t Sound_Volume_White = 0x01C48D;
  constexpr uint24_t Sound_Checkbox = 0x01CCCF;
  constexpr uint24_t Title = 0x01CCDD;
  constexpr uint24_t Select = 0x02105F;
  constexpr uint24_t HUD = 0x023221;
  constexpr uint24_t Score_Numbers_Bottom = 0x02344B;
  constexpr uint24_t Score_Numbers_Left = 0x023549;
  constexpr uint24_t Score_Numbers_Right = 0x023647;
  constexpr uint24_t Bid = 0x023745;
  constexpr uint24_t Arrows = 0x024113;
  constexpr uint24_t HighScores = 0x024163;
  constexpr uint24_t Dealer = 0x024B55;
  constexpr uint24_t Wave_Top = 0x024B66;
  constexpr uint24_t Wave_Bot = 0x025294;
  constexpr uint24_t Magnets = 0x0259C2;
  constexpr uint24_t Tile_0102 = 0x0264A4;
  constexpr uint24_t Tile_0403 = 0x02663E;
  constexpr uint24_t Tile_1112 = 0x0267D8;
  constexpr uint24_t Tile_2221 = 0x026A1A;
  constexpr uint24_t Tile_3132 = 0x026C5C;
  constexpr uint24_t Tile_4142 = 0x026DF6;
  constexpr uint24_t Tile_5152 = 0x027038;
  constexpr uint24_t Tile_6162 = 0x0271D2;
  constexpr uint24_t Cursor_X = 0x027414;
  constexpr uint24_t Cursor_Y = 0x027476;
  constexpr uint24_t Plus = 0x027484;
  constexpr uint24_t Minus = 0x02749E;
}

