#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.13 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xfed0;
constexpr uint24_t FX_DATA_BYTES = 73668;

constexpr uint16_t FX_SAVE_PAGE  = 0xfff0;
constexpr uint24_t FX_SAVE_BYTES = 2;

namespace Constants
{
  constexpr uint24_t temp_Count = 0x000000;
  constexpr uint24_t temp_6x5_00 = 0x000001;
  constexpr uint24_t temp_6x5_01 = 0x00001F;
  constexpr uint24_t temp_6x5_02 = 0x00003D;
  constexpr uint24_t temp_6x5_03 = 0x00005B;
  constexpr uint24_t temp_6x5_04 = 0x000079;
  constexpr uint24_t temp_6x5_05 = 0x000097;
  constexpr uint24_t temp_6x5_06 = 0x0000B5;
  constexpr uint24_t temp_6x5_07 = 0x0000D3;
  constexpr uint24_t temp_6x5_08 = 0x0000F1;
  constexpr uint24_t temp_6x5_09 = 0x00010F;
  constexpr uint24_t temp_6x5_10 = 0x00012D;
  constexpr uint24_t temp_6x5_11 = 0x00014B;
  constexpr uint24_t temp_8x7_00 = 0x000169;
  constexpr uint24_t temp_8x7_01 = 0x0001A1;
  constexpr uint24_t temp_8x7_02 = 0x0001D9;
  constexpr uint24_t temp_8x7_03 = 0x000211;
  constexpr uint24_t temp_8x7_04 = 0x000249;
  constexpr uint24_t temp_8x7_05 = 0x000281;
  constexpr uint24_t temp_8x7_06 = 0x0002B9;
  constexpr uint24_t temp_8x7_07 = 0x0002F1;
  constexpr uint24_t temp_8x7_08 = 0x000329;
  constexpr uint24_t temp_8x7_09 = 0x000361;
  constexpr uint24_t temp_8x7_10 = 0x000399;
  constexpr uint24_t temp_8x7_11 = 0x0003D1;
  constexpr uint24_t temp_10x9_00 = 0x000409;
  constexpr uint24_t temp_10x9_01 = 0x000463;
  constexpr uint24_t temp_10x9_02 = 0x0004BD;
  constexpr uint24_t temp_10x9_03 = 0x000517;
  constexpr uint24_t temp_10x9_04 = 0x000571;
  constexpr uint24_t temp_10x9_05 = 0x0005CB;
  constexpr uint24_t temp_10x9_06 = 0x000625;
  constexpr uint24_t temp_10x9_07 = 0x00067F;
  constexpr uint24_t temp_10x9_08 = 0x0006D9;
  constexpr uint24_t temp_10x9_09 = 0x000733;
  constexpr uint24_t temp_10x9_10 = 0x00078D;
  constexpr uint24_t temp_10x9_11 = 0x0007E7;
  constexpr uint24_t temp_Levels = 0x000841;
}

namespace Images
{
  constexpr uint24_t PPOT = 0x0008AD;
  constexpr uint24_t Sound_Checkbox = 0x0038AF;
  constexpr uint24_t Title = 0x0038BD;
  constexpr uint24_t Select = 0x00613F;
  constexpr uint24_t Hooray_00 = 0x008301;
  constexpr uint24_t Hooray_01 = 0x0084B3;
  constexpr uint24_t Hooray_02 = 0x0086F5;
  constexpr uint24_t Hooray_03 = 0x008937;
  constexpr uint24_t Hooray_04 = 0x008AD1;
  constexpr uint24_t Hooray_05 = 0x008C83;
  constexpr uint24_t Hooray_06 = 0x008E35;
  constexpr uint24_t HUD = 0x008EDF;
  constexpr uint24_t Score_Numbers_Bottom = 0x009109;
  constexpr uint24_t Score_Numbers_Left = 0x009207;
  constexpr uint24_t Score_Numbers_Right = 0x009305;
  constexpr uint24_t Arrows = 0x009403;
  constexpr uint24_t HighScores = 0x009453;
  constexpr uint24_t Dealer = 0x009E45;
  constexpr uint24_t Wave_Top = 0x009E56;
  constexpr uint24_t Wave_Bot = 0x00A584;
  constexpr uint24_t Wave_Left = 0x00ACB2;
  constexpr uint24_t Wave_Right = 0x00B290;
  constexpr uint24_t Magnets = 0x00B86E;
  constexpr uint24_t InGame = 0x00C350;
  constexpr uint24_t InGame_Solid = 0x00D73E;
  constexpr uint24_t Tile_0102 = 0x00F120;
  constexpr uint24_t Tile_0403 = 0x00F452;
  constexpr uint24_t Tile_1112 = 0x00F784;
  constexpr uint24_t Tile_2221 = 0x00FC06;
  constexpr uint24_t Tile_3132 = 0x010088;
  constexpr uint24_t Tile_4142 = 0x0103BA;
  constexpr uint24_t Tile_5152 = 0x01083C;
  constexpr uint24_t Tile_6162 = 0x010B6E;
  constexpr uint24_t Cursor_X = 0x010FF0;
  constexpr uint24_t Cursor_Y = 0x011052;
  constexpr uint24_t Plus = 0x011060;
  constexpr uint24_t Minus = 0x01107A;
  constexpr uint24_t Arrow = 0x011094;
  constexpr uint24_t Hints = 0x0110A2;
  constexpr uint24_t Hints_Solid = 0x011AB8;
}

